
export const MOCK_USERS = Array.from({ length: 50 }).map((_, index) => ({
    id: index + 1,
    name: `Nombres ${index + 1}`,
    lastname: `Apellidos ${index + 1}`,
    phone: `3202090322`,
    email: `usuario${index + 1}@example.com`,
    school: `Colegio ${index + 1}`,
    city: `Ciudad ${index + 1}`,
    province: `Depart ${index + 1}`,
    sales: index,
    totalSales: `$ ${index}.000`,
  }));

export const MOCK_PACKAGES = Array.from({ length: 25 }).map((_, index) => ({
  id: index + 1,
  date: `21-02-2026`,
  title: `Title ${index + 1}`,
  description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor ullamcorper erat volutpat fringilla. Curabitur viverra imperdiet dui, eu tincidunt nisl ultricies vitae. Aliquam fermentum purus vitae enim dapibus facilisis ${index + 1}.`,
  subject: `Matematicas`,
  grade: `Grado ${index + 1}`,
  status: `Activo`,
  price: `$ ${index}.000`,
  documents: 7,
}));

export const MOCK_DOCUMENTS = Array.from({ length: 25 }).map((_, index) => ({
  id: index + 1,
  type: `Taller ${index + 1}`,
  description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor ullamcorper erat volutpat fringilla. Curabitur viverra imperdiet dui, eu tincidunt nisl ultricies vitae. Aliquam fermentum purus vitae enim dapibus facilisis ${index + 1}.`,
  subject: `Matematicas`,
  grade: `Grado ${index + 1}`,
  status: `Libre`,
  url: `www.text.com.co`,
  packages: 7,
}));

export const MOCK_BILLING = Array.from({ length: 25 }).map((_, index) => ({
  id: index + 1,
  date: `21-02-2026`,
  package: `Paquete ${index + 1}`,
  ticketId: `TicketId ${index + 1}`,
  name: `Nombres ${index + 1}`,
  lastname: `Apellidos ${index + 1}`,
  email: `usuario${index + 1}@example.com`,
  status: `Activo`,
  support: `www.text.com.co`,
  value: `$ ${index}.000`,
  notes: `Lorem ipsum dolor sit amet, consectetur adipiscing elit ${index + 1}.`,
}));

export const MOCK_USERS_DB = [
  {
    serial: 1,
    name: `Nombres 1`,
    lastname: `Apellidos 1`,
    cellphone: `3202090322`,
    email: `usuario1@example.com`,
    school: `Colegio 1`,
    city: `Ciudad 1`,
    province: `Huila`,
    sales_qty : 10,
    sales_total: `$ 10.000`,
    date: new Date(),
  },
  {
    serial: 2,
    name: `Nombres 2`,
    lastname: `Apellidos 2`,
    cellphone: `3202090320`,
    email: `usuario2@example.com`,
    school: `Colegio 2`,
    city: `Ciudad 2`,
    province: `Huila`,
    sales_qty: 20,
    sales_total: `$ 20.000`,
    date: new Date(),
  },
  {
    serial: 3,
    name: `Nombres 3`,
    lastname: `Apellidos 3`,
    cellphone: `3202090321`,
    email: `usuario3@example.com`,
    school: `Colegio 3`,
    city: `Ciudad 3`,
    province: `Huila`,
    sales_qty: 30,
    sales_total: `$ 30.000`,
    date: new Date(),
  },
  {
    serial: 4,
    name: `Nombres 4`,
    lastname: `Apellidos 4`,
    cellphone: `3202090323`,
    email: `usuario4@example.com`,
    school: `Colegio 4`,
    city: `Ciudad 4`,
    province: `Huila`,
    sales_qty: 40,
    sales_total: `$ 40.000`,
    date: new Date(),
  },
  {
    serial: 5,
    name: `Nombres 5`,
    lastname: `Apellidos 5`,
    cellphone: `3202090324`,
    email: `usuario5@example.com`,
    school: `Colegio 5`,
    city: `Ciudad 5`,
    province: `Huila`,
    sales_qty: 50,
    sales_total: `$ 50.000`,
    date: new Date(),
  },
  {
    serial: 6,
    name: `Nombres 6`,
    lastname: `Apellidos 6`,
    cellphone: `3202090325`,
    email: `usuario6@example.com`,
    school: `Colegio 6`,
    city: `Ciudad 6`,
    province: `Huila`,
    sales_qty: 60,
    sales_total: `$ 60.000`,
    date: new Date(),
  },      
  {
    serial: 7,
    name: `Nombres 7`,
    lastname: `Apellidos 7`,
    cellphone: `3202090326`,
    email: `usuario7@example.com`,
    school: `Colegio 7`,
    city: `Ciudad 7`,
    province: `Huila`,
    sales_qty: 70,
    sales_total: `$ 70.000`,
    date: new Date(),
  },
  {
    serial: 8,
    name: `Nombres 8`,
    lastname: `Apellidos 8`,
    cellphone: `3202090327`,
    email: `usuario8@example.com`,
    school: `Colegio 8`,
    city: `Ciudad 8`,
    province: `Huila`,
    sales_qty: 80,
    sales_total: `$ 80.000`,
    date: new Date(),
  },
  {
    serial: 9,
    name: `Nombres 9`,
    lastname: `Apellidos 9`,
    cellphone: `3202090328`,
    email: `usuario9@example.com`,
    school: `Colegio 9`,
    city: `Ciudad 9`,
    province: `Huila`,
    sales_qty: 90,
    sales_total: `$ 90.000`,
    date: new Date(),
  },
  {
    serial: 10,
    name: `Nombres 10`,
    lastname: `Apellidos 10`,
    cellphone: `3202090329`,
    email: `usuario10@example.com`,
    school: `Colegio 10`,
    city: `Ciudad 10`,
    province: `Huila`,
    sales_qty: 100,
    sales_total: `$ 100.000`,
    date: new Date(),
  },
]

export const MOCK_BILLING_DB = [
  {
    serial: 12,
    date_purchase: new Date(),
    invoice: {
      id: `I0002`,
      url: `www.text.com.co`,
      pathname: `billing/factura2`,
      name: `Factura 2`,
    },
    notes: `Lorem ipsum dolor sit amet, consectetur adipiscing elit 2.`,
    packages: [
      {
        id: `P0002`,
        title: `Taller 2`,
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit 2.`,
        price: `$ 10.000`,
      },
      {
        id: `P0003`,
        title: `Taller 3`,
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit 3.`,
        price: `$ 10.000`,
      },
    ],
    user: {
      id: `U0002`,
      name: `Nombres 2`,
      lastname: `Apellidos 2`,
      email: `usuario2@example.com`,
      phone: `3202090320`,
    },
    status: `Pendiente`,
    ticket_id: `T0002`,
    total_cost: 10000,
    total_packages: 2,
    user: {
      id: `U0002`,
      name: `Nombres 2`,
      lastname: `Apellidos 2`,
      email: `usuario2@example.com`,
      phone: `3202090320`,
    },
  },
  {
    serial: 13,
    date_purchase: new Date(),
    invoice: {
      id: `I0003`,
      url: `www.text.com.co`,
      pathname: `billing/factura3`,
      name: `Factura 3`,
    },
    notes: `Lorem ipsum dolor sit amet, consectetur adipiscing elit 3.`,
    packages: [
      {
        id: `P0003`,
        title: `Taller 3`,
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit 3.`,
        price: `$ 10.000`,
      },
    ],
    user: {
      id: `U0003`,
      name: `Nombres 3`,
      lastname: `Apellidos 3`,
      email: `usuario2@example.com`,
      phone: `3202090322`,
    },
    status: `Pendiente`,
    ticket_id: `T0003`,
    total_cost: 10000,
    total_packages: 1,
  },
  {
    serial: 14,
    date_purchase: new Date(),
    invoice: {
      id: `I0004`,
      url: `www.text.com.co`,
      pathname: `billing/factura4`,
      name: `Factura 4`,
    },
    notes: `Lorem ipsum dolor sit amet, consectetur adipiscing elit 4.`,
    packages: [
      {
        id: `P0004`,
        title: `Taller 4`,
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit 4.`,
        price: `$ 10.000`,
      },
    ],
    user: {
      id: `U0004`,
      name: `Nombres 4`,
      lastname: `Apellidos 4`,
      email: `usuario2@example.com`,
      phone: `3202090322`,
    },
    status: `Pagado`,
    ticket_id: `T0004`,
    total_cost: 10000,
    total_packages: 1,
  },
  {
    serial: 15,
    date_purchase: new Date(),
    invoice: {
      id: `I0005`,
      url: `www.text.com.co`,
      pathname: `billing/factura5`,
      name: `Factura 5`,
    },
    notes: `Lorem ipsum dolor sit amet, consectetur adipiscing elit 5.`,  
    packages: [
      {
        id: `P0005`,
        title: `Taller 5`,
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit 5.`,
        price: `$ 10.000`,
      },
    ],
    user: {
      id: `U0005`,
      name: `Nombres 5`,
      lastname: `Apellidos 5`,
      email: `usuario5@example.com`,
      phone: `3202090324`,
    },
    status: `Pendiente`,
    ticket_id: `T0005`,
    total_cost: 10000,
    total_packages: 1,
  },
  {
    serial: 16,
    date_purchase: new Date(),
    invoice: {
      id: `I0006`,
      url: `www.text.com.co`,
      pathname: `billing/factura6`,
      name: `Factura 6`,
    },
    notes: `Lorem ipsum dolor sit amet, consectetur adipiscing elit 6.`,
    packages: [
      {
        id: `P0006`,
        title: `Taller 6`,
        description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit 6.`,
        price: `$ 10.000`,
      },
    ],
    user: {
      id: `U0006`,
      name: `Nombres 6`,
      lastname: `Apellidos 6`,
      email: `usuario6@example.com`,
      phone: `3202090325`,
    },
    status: `Pendiente`,
    ticket_id: `T0006`,
    total_cost: 10000,
    total_packages: 1,
  },
]